### ISSUE TITLE
Navigate to Project Page After Deleting Parcel

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#122]
### Subject of the issue
We have users who delete parcels fully from their assets if they aren't feasible for development rather than from just the project to keep the assets page clean. 

However, when you delete a parcel from it's asset detail page, the application navigates the user back to the assets list page, so the user has to manually navigate back to the proper project and pick up where they left off. This can be cumbersome and take numerous clicks. 

User's also want to return to the same spot in their search as outlined in #123 

### Feature Request

Can you make it so that when a user delete's a parcel from its asset detail page, the application navigates the user back to the project detail page of a project it's a part of. 

If it's a part of multiple projects, maybe default to the most recent project or display a prompt that gives the option. Trust your judgement on best methodology

**Comment by eanderson4** [comment]
I'm thinking the best way to do this will just be to have the browser navigate 'back' after an item is deleted.  

I'm guessing part of the issue is it navigates to asset list page, and then the back button attempts to route to a page that doesn't exist, so it navigates back to the asset list page, which ruins the back button behavior.

The new approach will fix this.

Another approach is to not reroute when the asset doesn't exist, instead just display an asset doesn't exist message.  This would at least preserve the back button behavior and allow you to get back to your project.

**Comment by jakebanderson321** [comment]
Yes, I agree that simply triggering a "Back" to go back to the project detail page makes sense and should cover the primary use case. 

We should also include a refresh or else the user will be confused when the parcel still shows in the list. (If a refresh isn't needed to make sure the parcel doesn't show, disregard this note)

The first approach is better. I don't think they're leveraging the back button. I think once they land on on the asset list page, they just navigate to their project page and select the project from there, so they're going into it from the "front" again.

**Comment by eanderson4** [comment]
Sounds good, they are both in the latest release.  In general, anything that breaks the back button should be considered a bug.  Let me know what you think.

**Comment by jakebanderson321** [comment]
Looks good. Good to know on breaking back button.
