### ISSUE TITLE
Multi-Color Marker drop

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#6]
### Feature Request
Create the ability to adjust the colors of markers dropped onto the map.

Create the ability to save those colors as presets.

**Comment by eanderson4** [comment]
Feature added to dev version 

Ability to customize marker url, width, and height were added.  
Ability to change default markers via map style config was added.
Ability to save element styles as presets was added.

To fully answer the adjusting of colors for markers, we may need a little more work.  Today, we can do it in a round about way by using this as marker url.

https://mt.google.com/vt/icon/text=E&psize=16&font=fonts/arialuni_t.ttf&color=ff330000&name=icons/spotlight/spotlight-waypoint-b.png&ax=44&ay=48&scale=1

Color can be changed in hex notation to create different color markers.  These can then be saved through the preset system.  To get this setup takes some work initially.

This will require some testing as well, since I made some significant changes to how styles are applied in order to get in all to work.

**Comment by eanderson4** [comment]
Here is stack overflow resource on this google icon tool
https://stackoverflow.com/questions/17746740/google-map-icons-with-visualrefresh

**Comment by eanderson4** [comment]
I've added simple previews of styles in latest release

![image](https://user-images.githubusercontent.com/5291870/46650751-f902b700-cb5a-11e8-92f0-ac57378e4859.png)

**Comment by eanderson4** [comment]
The work on this had created another issue where the copied elements style was not saved.  This should be fixed in latest version 3.3-31

**Comment by eanderson4** [comment]
Another marker icon resource

https://github.com/Concept211/Google-Maps-Markers

**Comment by jakebanderson321** [comment]
How difficult would it be to put in a "Duplicate polygon or marker" button, so that if there are numerous of the same feature on a site, user wouldn't have to manually draw each one and could instead duplicate and move?

**Comment by jakebanderson321** [comment]
Works fine but get the following error. Not sure if this is affecting anything but wanted to mention just in case.


![screen shot 2018-10-16 at 12 21 04 pm](https://user-images.githubusercontent.com/13791320/47034836-0a8d2580-d13e-11e8-83ce-a4b57f1d1bd7.png)

**Comment by eanderson4** [comment]
We can add copy/duplicate feature to elements.  Create another feature request for this as it will go into a future release.

I'll try and handle those errors better, they do pop up from time to time and it is not directly related to this issue I believe.

**Comment by eanderson4** [comment]
I can't reproduce this currently so I'm going to close this. Feel free to open a new issue with additional details on the error.
